---
functional:
  - Пользователь должен иметь возможность регистрироваться и авторизовываться
  - Пользователь должен иметь возможность менять настройки своего профиля
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока
  - Пользователь должен иметь возможность видеть код своего соперника в режиме он-лайн  
  - Пользователь должен иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность выбрать игру по уровню сложности
  - Пользователь должен иметь возможность выбрать время ограничения игры, она может длиться неограниченное время
  - Пользователь должен иметь возможность переподключиться в игру в любой момент, пока она не закончена, если он вылетел из нее
  - Пользователь должен видеть задачи на двух языках — русском и английском
  - Пользователь должен иметь возможность следить за ходом чужой игры
  - Пользователь должен иметь кнопку 'check' для проверки своего решения, попыток проверки неограниченно
  - Зарегистрированный пользователь должен иметь возможность общаться с другими пользователями в чате
  - Завершенная игра должна быть доступна в записи
  - Пользователь должен иметь возможность получать очки, на основе которых должен строиться рейтинг за неделю, месяц и за все время
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь не может создать игру при наличии незавершенной ранее созданной
